
## use predefined project file (don't create one).  Needs include path hard coded.

all:
	echo "Using Makefile.win" 
	cp qtutils.pro.win qtutils.pro
	qmake -o Makefile.qtutils
	sh ./replace.sh Makefile.qtutils
	sh ./replace.sh Makefile.qtutils.Release
	sh ./replace.sh Makefile.qtutils.Debug
	make -f Makefile.qtutils
	cp release/* .

clean:
	echo "Using Makefile.win" 
	rm -rf *.so *.o *.a *.dll Makefile.qt* qtutils.pro libqt* moc*.cpp debug release *~
